### ISSUE TITLE
Build simple data extraction, validation and preparation logic using Colab

### ISSUE THREAD

**Issue by edwardlach** [sweng480-team23/tweetqa-pipeline#4]
Write a first draft of data extraction, validation and preparation using the Tweet QA data in Colab.  The output off this work should have the data in a state that can be passed directly to a model training process.

**Comment by edwardlach** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/TweetQA-61436aca71c16d001e080380/issues/sweng480-team23/tweetqa-pipeline/4?planning-poker) with ZenHub @lwestfall @sjchin88 @zacherysmith115

**Comment by lwestfall** [comment]
Made a new notebook for this, I think I'm on the right track, not totally sure if there's anything else required here but we should discuss in the next meeting. I wanted to try training a BERT model on it to make sure the data is formatted correctly but got stuck and gave up, and that's a whole other task anyway.

Here is the notebook (can also be found in the shared drive -> Google Colabs):
https://colab.research.google.com/drive/1RDCgrnklTl8GkbvR6S3Er2w-E2-Vdmte?usp=sharing
